/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 16 16:23:26 GMT 2023
 */

package Model.Tests.Test;

import Model.Tests.Scaffolding.CasaInteligenteAlreadyExistsException_ESTest_scaffolding;
import org.junit.Test;
import Model.Exceptions.CasaInteligenteAlreadyExistsException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CasaInteligenteAlreadyExistsException_ESTest extends CasaInteligenteAlreadyExistsException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CasaInteligenteAlreadyExistsException casaInteligenteAlreadyExistsException0 = new CasaInteligenteAlreadyExistsException("6");
  }
}
